@baseUrl = http://localhost:4000/api/all

# Categories

# @name getAllCategories
# GET {{baseUrl}}/products?_limit=2&_page=1
# GET {{baseUrl}}/products?name_like=bánh&_limit=2&_page=1
GET {{baseUrl}}/users

###
# @name getAllCategories
GET {{baseUrl}}/products?category=combo,

###

# @name addNewCategory
POST {{baseUrl}}/users
Content-Type: application/json


{
    
    "email" : "leducnghi28122000hiie@gmail.com",
    "password" : "0972647481nghi",
    "username" : "Duc Nghi",
    "age" : 32,
    "role" : "admin",
    "phone" : "0338006534"
}

###

# @name updateCategory
PATCH {{baseUrl}}/categories/2
Content-Type: application/json

{
  "name": "New Laptop"
}

###

# @name removeCategory
DELETE {{baseUrl}}/users/5
