@baseUrl = http://localhost:4000
@resourceName = posts

# @name getAllCategory
# GET {{baseUrl}}/{{resourceName}}
PATCH {{baseUrl}}/api/bill/bills/1
Content-Type: application/json

{
  "status" : "Received"
}

###

# @name filtersProducts
GET {{baseUrl}}/{{resourceName}}?prices_gte=900
Content-Type: application/json

{
    "body" : "le duc nghi"
}


###

# @name updateCategory
PATCH  {{baseUrl}}/{{resourceName}}/2
Content-Type: application/json

{
    "body" : "le duc nghi 2"
}

###

# @name removeCategory
DELETE {{baseUrl}}/{{resourceName}}/2
